### ISSUE TITLE
Missing file data/vocabulary.log

### ISSUE THREAD

**Issue by JulianZhang** [stefanthaler/2017-fnlm-experiments-supervised#1]
Dear

I'm trying to run the script 100 and 101,but all fail because missing file data/vocabulary.log.

#python 100_crossvalidate-bilstm-charmodel.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "100_crossvalidate-bilstm-charmodel.py", line 34, in <module>
    token_vocabulary = create_vocabulary_from( vocab_file , add_unk=True )
  File "/home/zhangjun/2017-fnlm-experiments-supervised-master/helpers/vocabularies.py", line 4, in create_vocabulary_from
    with open(file_name, "r") as input_file:
IOError: [Errno 2] No such file or directory: 'data/vocabulary.log'

#python 101_train-bilstm-charmodel.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "101_train-bilstm-charmodel.py", line 37, in <module>
    token_vocabulary = create_vocabulary_from( vocab_file , add_unk=True )
  File "/home/zhangjun/2017-fnlm-experiments-supervised-master/helpers/vocabularies.py", line 4, in create_vocabulary_from
    with open(file_name, "r") as input_file:
IOError: [Errno 2] No such file or directory: 'data/vocabulary.log'

**Comment by JulianZhang** [comment]
Dear @stefanthaler can you help me to run the script?

**Comment by stefanthaler** [comment]
Hi Julian, sorry for the delayed response.

I've fixed the mistake, see commit 813fd94. Vocabulary log is just a file that contains all the characters that are used in your learning. 

Alternatively you can also create a vocabulary.log by 'cat train_logfile.txt test_logfile.txt > vocabulary.log'  or by, e.g. creating a vocabulary.log by adding all the characters that you want to consider. 

cheers,
Stefan
